INSERT INTO public.users (id, description, email, image, image_uri, password, token, username, role) VALUES (5, null, 'marcoreus@yahoo.com', null, null, '$2a$10$ePAaHwBatsaODPhWKOmC8OcV/XoVYaZQNrL31JAiP1Y8ImIgCJxDO', 'eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYXJjb3JldXNAeWFob28uY29tIiwiaWQiOjUsImVtYWlsIjoibWFyY29yZXVzQHlhaG9vLmNvbSIsInVzZXJuYW1lIjoiTWFyY28gUmV1cyIsImlhdCI6MTY4NzI4NTEyMCwiZXhwIjoxNjg4Mjg1MTIwfQ.eLneG3vDnATlBvP2XbRQy4wJ4QmJtzgAztPwPHbX_Y4', 'Ionel Popescu', 1);
INSERT INTO public.users (id, description, email, image, image_uri, password, token, username, role) VALUES (4, null, 'emma@yahoo.com', null, null, '$2a$10$ST2NZRiz2RkfK6hEmaVHyuvFJjqRyRbeODjQ4JfPIy5nvFv5JI65a', 'eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJlbW1hQHlhaG9vLmNvbSIsImlkIjo0LCJlbWFpbCI6ImVtbWFAeWFob28uY29tIiwidXNlcm5hbWUiOiJFbWEgQWxleGFuZHJhIiwiaWF0IjoxNjg3NDYxOTU4LCJleHAiOjE2ODg0NjE5NTh9.-daChQWpybNdGf76ZJIBIx-X4KYXvVWJuGqE6BqwQsI', 'Ema Alexandra', 1);
INSERT INTO public.users (id, description, email, image, image_uri, password, token, username, role) VALUES (2, null, 'lenghelionut@yahoo.com', null, null, '$2a$10$AHWbmJpUviw1.tyw7vpvSuJkIjB6aDy8dfwlFo130Q2xyph475P8G', 'eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJsZW5naGVsaW9udXRAeWFob28uY29tIiwiaWQiOjIsImVtYWlsIjoibGVuZ2hlbGlvbnV0QHlhaG9vLmNvbSIsInVzZXJuYW1lIjoiSW9udXQgQW5kcmVpIiwiaWF0IjoxNjg3NDYxOTk5LCJleHAiOjE2ODg0NjE5OTl9.8aXao5FE2GTMsoHunmk9ONXxo01hslFftKLM-Uo-Otk', 'Ionut Andrei', 1);
INSERT INTO public.users (id, description, email, image, image_uri, password, token, username, role) VALUES (1, null, 'margotrobbie@yahoo.com', null, null, '$2a$10$8MoDacnJkGbks96pPq0VOumqirdl6csOiYihNYqLkfxder7QNCnuO', 'eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYXJnb3Ryb2JiaWVAeWFob28uY29tIiwiaWQiOjEsImVtYWlsIjoibWFyZ290cm9iYmllQHlhaG9vLmNvbSIsInVzZXJuYW1lIjoiQW5hIElvbmVzY3UiLCJpYXQiOjE2ODc0NjIwMTcsImV4cCI6MTY4ODQ2MjAxN30.tfUfteRheAMnlk-FYmm7UO5n6ZA151bzy2QFrsFE1Ik', 'Ana Ionescu', 1);
INSERT INTO public.users (id, description, email, image, image_uri, password, token, username, role) VALUES (3, null, 'jennaortega@yahoo.com', null, null, '$2a$10$rZx8rc9ZYtsjXbwHPMuSbuI8X9aRrQxsj7V4Sz4MOPbrL4rUNU7Sq', 'eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqZW5uYW9ydGVnYUB5YWhvby5jb20iLCJpZCI6MywiZW1haWwiOiJqZW5uYW9ydGVnYUB5YWhvby5jb20iLCJ1c2VybmFtZSI6IkVsZW5hIEdlb3JnZXNjdSIsImlhdCI6MTY4NzQ2Mjk5MSwiZXhwIjoxNjg4NDYyOTkxfQ.BGBFqK69AC1ELSvIlazNx3PU3xi_jCYpfYNNoFavHNM', 'Elena Georgescu', 1);

INSERT INTO public.connections (id, user1response, user2response, app_user1_id, app_user2_id) VALUES (79, 'NO', null, 1, 4);
INSERT INTO public.connections (id, user1response, user2response, app_user1_id, app_user2_id) VALUES (80, 'YES', null, 1, 5);
INSERT INTO public.connections (id, user1response, user2response, app_user1_id, app_user2_id) VALUES (82, 'NO', null, 1, 2);
INSERT INTO public.connections (id, user1response, user2response, app_user1_id, app_user2_id) VALUES (84, 'YES', null, 3, 5);
INSERT INTO public.connections (id, user1response, user2response, app_user1_id, app_user2_id) VALUES (81, 'YES', 'YES', 1, 3);
INSERT INTO public.connections (id, user1response, user2response, app_user1_id, app_user2_id) VALUES (87, 'YES', null, 2, 5);
INSERT INTO public.connections (id, user1response, user2response, app_user1_id, app_user2_id) VALUES (85, 'YES', 'YES', 3, 2);
INSERT INTO public.connections (id, user1response, user2response, app_user1_id, app_user2_id) VALUES (88, 'YES', null, 4, 5);
INSERT INTO public.connections (id, user1response, user2response, app_user1_id, app_user2_id) VALUES (83, 'YES', 'YES', 3, 4);
INSERT INTO public.connections (id, user1response, user2response, app_user1_id, app_user2_id) VALUES (86, 'YES', 'YES', 2, 4);
