server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: postgres_chs
    url: jdbc:postgresql://localhost:5432/chs_db
    username: postgres_chs
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
    show-sql: true
